FROM node:22-bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends git ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /volume1/docker/nas-webhook

COPY webhook.js /volume1/docker/nas-webhook/webhook.js
COPY merge.js /volume1/docker/nas-webhook/merge.js

CMD ["node", "webhook.js"]
